 services:

  apache:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - ./db:/var/lib/mariadb
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 81:80