 version: "3"
 services:

  apache:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      container_name: phpmyadmin_service
      UPLOAD_LIMIT: 1G
    env_file:
     - .env