 version: "3"
 services:

  apache:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST

  db:
    image: arm64v8/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dev
  phpmyadmin:
    image: arm64v8/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 81:80